Repository US-CBP/GTAS-UI, pull requests merged in 2020-07, with the labels that each got.

#86 auditfix - 5037 fixes in 2271 packages
  package-lock.json
  yarn.lock
Labels: 3 - Review

#87 Feature/adminheader
  src/components/header/Header.js
  src/components/title/Title.css
  src/pages/admin/Admin.js
  src/pages/admin/codeEditor/CodeEditor.js
  src/pages/admin/fileDownload/FileDownload.js
  src/pages/admin/fileDownload/fileDownload.css
  src/pages/admin/loaderStats/LoaderStats.js
  src/pages/admin/manageUsers/ManageUsers.js
  src/pages/admin/noteTypeCats/NoteTypeCats.js
  src/pages/admin/settings/Settings.js
  src/pages/admin/watchlistCats/WatchlistCats.js
  src/pages/tools/queryrules/Queries.js
  src/pages/tools/queryrules/Rules.js
  src/pages/tools/watchlist/Watchlist.js
Labels: 3 - Review, enhancement

#94 Fix/segmenttable
  src/components/segmentTable/SegmentTable.js
  src/pages/tools/queryrules/QRDetails.js
  src/pages/tools/queryrules/QRModal.js
Labels: 3 - Review, bug

#95 fix #85 and update roles layout to 3 cols to save vertical space
  src/pages/admin/manageUsers/ManageUsers.scss
  src/pages/admin/manageUsers/UserModal.js
Labels: 3 - Review, enhancement

#105 Header - mark the admin and tools menus when subitems are selected
  src/components/header/Header.js
Labels: 1 - Ready, enhancement

#100 User registration
  src/App.js
  src/components/header/Header.js
  src/pages/admin/signUpRequests/SignUpRequests.js
  src/pages/login/Login.js
  src/pages/signUp/SignUp.js
  src/pages/signUp/SignUp.scss
  src/services/serviceWrapper.js
Labels: enhancement
