Repository US-CBP/GTAS-UI, pull requests merged in 2020-08, with the labels that each got.

#120 update parents of Form component for new callback
  src/pages/admin/manageUsers/UserModal.js
  src/pages/admin/manageUsers/changePassword/ChangePassword.js
  src/pages/admin/noteTypeCats/NoteTypeModal.js
  src/pages/admin/settings/Settings.js
  src/pages/admin/watchlistCats/WatchlistModal.js
  src/pages/paxDetail/addToWatchList/AddToWatchlist.js
  src/pages/paxDetail/createManualHit/CreateManualHit.js
  src/pages/paxDetail/evenNotesModal/EventNotesModal.js
  src/pages/signUp/SignUp.js
  src/pages/tools/watchlist/WLModal.js
Labels: bug

#101 Feature/rules
  src/App.js
  src/components/labelledInput/LabelledInput.css
  src/components/queryBuilder/QueryBuilder.js
  src/components/queryBuilder/constants.js
  src/pages/admin/manageUsers/UserModal.js
  src/pages/tools/queryrules/QRDetails.js
  src/pages/tools/queryrules/QRModal.js
  src/pages/tools/queryrules/Queries.js
  src/pages/tools/queryrules/QueryRules.css
  src/pages/tools/queryrules/Rules.js
  src/pages/tools/rules/Rules.js
  src/services/serviceWrapper.js
  src/utils/constants.js
Labels: 2 - Working <= 5

#129 fix state issues in Rules
  src/components/queryBuilder/QBUtils.js
  src/pages/tools/queryrules/Rules.js
Labels: bug

#133 Password reset
  src/App.js
  src/pages/admin/manageUsers/changePassword/ChangePassword.scss
  src/pages/admin/manageUsers/changePassword/ForgotPassword.js
  src/pages/admin/manageUsers/changePassword/ResetPassword.js
  src/pages/login/Login.js
  src/services/serviceWrapper.js
Labels: 3 - Review, enhancement

#96 Front-end changes req'd for new Archive/Delete user functionality
  src/pages/admin/manageUsers/ManageUsers.js
  src/pages/admin/manageUsers/UserModal.js
  src/pages/quickQuery/QuickQuery.js
  src/pages/seatsMap/SeatsMap.js
  src/services/serviceWrapper.js
Labels: 2 - Working <= 5, backend, database

#165 init bundle reorg. Must run yarn install for new deps
  package.json
  src/App.js
  src/components/graph/Graph.js
  src/pages/login/ForgotPassword.js
  src/pages/login/ResetPassword.js
  src/pages/tools/queryrules/Rules.js
  yarn.lock
Labels: 1 - Ready, enhancement
