Repository US-CBP/GTAS-UI, pull requests merged in 2020-11, with the labels that each got.

#367 Fix/datepickerlayout
  src/components/filterForm2/FilterForm.css
  src/components/sidenavContainer/SidenavContainer.scss
  src/pages/vetting/Vetting.css
Labels: 2.0, bug

#368 fix the width on the last modal
  src/pages/vetting/review/Review.js
Labels: 2.0 Burndown, bug

#373 align flightbadge data, format popover link
  src/App.css
  src/components/cardWithTable/CardWithTable.js
  src/components/confirmationModal/Confirm.js
  src/components/flightBadge/FlightBadge.js
  src/components/flightBadge/FlightBadge.scss
  src/components/overlay/Overlay.scss
  src/components/paxInfo/PaxInfo.js
  src/components/paxInfo/PaxInfo.scss
  src/images/plane-arrival-solid.svg
  src/images/plane-departure-solid.svg
  src/pages/tools/queryrules/QRModal.js
  src/pages/tools/queryrules/QueryRules.css
  src/pages/vetting/Vetting.css
  src/pages/vetting/Vetting.js
  src/pages/vetting/flightInfo/FlightInfo.js
Labels: 2.0 Burndown, bug

#377 fix note input style
  src/pages/paxDetail/notification/Notification.js
Labels: 2.0 Burndown, bug

#382 force read mode on logout
  src/components/header/Header.js
Labels: 2.0 Burndown, enhancement

#385 fix initial tab data fetch
  src/pages/tools/queryrules/Rules.js
Labels: 2.0 Burndown, bug

#381 center modals
  src/App.css
  src/components/graph/Graph.js
  src/context/translation/LiveEditContext.js
  src/pages/admin/manageUsers/changePasswordModal/ChangePasswordModal.js
  src/pages/lang/LanguageEditor.js
  src/pages/paxDetail/PaxDetail.js
Labels: 2.0 Burndown, bug

#384 fix forms errors, add spinners
  src/components/form/Form.js
  src/components/table/Table.js
  src/pages/admin/loaderStats/LoaderStats.js
  src/pages/admin/settings/Settings.js
  src/services/serviceWrapper.js
Labels: 2.0 Burndown, bug

#406 Fix/qbrb bags
  src/components/raqb/constants.js
  src/components/raqb/utils.js
  src/pages/tools/queryrules/QRModal.js
  src/pages/tools/queryrules/QueryRules.css
  src/pages/tools/queryrules/Rules.js
Labels: 2.0 Burndown

#371 Fix/search result
  src/pages/search/Search.js
Labels: backend

#439 fix date format, disable action col sort
  src/pages/admin/fileDownload/FileDownload.js
Labels: 3 - Review

#480 Fix/paxdetails
  src/components/flightBadge/FlightBadge.js
  src/pages/paxDetail/PaxDetail.js
  src/pages/paxDetail/flightHistory/FlightHistory.js
  src/pages/paxDetail/pnr/PNR.js
  src/pages/paxDetail/summary/Summary.js
  src/services/serviceWrapper.js
Labels: backend

#488 Feat/fab
  package-lock.json
  package.json
  src/App.css
  src/components/CSVReader/CSVReader.js
  src/components/eventNotesModal/EventNotesModal.js
  src/components/flightBadge/FlightBadge.scss
  src/components/sidenavContainer/SidenavContainer.scss
  src/components/stepper/Stepper.scss
  src/pages/admin/codeEditor/CodeEditor.js
  src/pages/admin/codeEditor/airport/Airport.js
  src/pages/admin/codeEditor/carrier/Carrier.js
  src/pages/admin/codeEditor/country/Country.js
  src/pages/admin/codeEditor/creditcardtype/CreditCardType.js
  src/pages/admin/hitCats/HitCats.js
  src/pages/admin/manageUsers/ManageUsers.js
  src/pages/admin/noteCats/NoteCats.js
  src/pages/flightPax/FlightPax.js
  src/pages/paxDetail/PaxDetail.js
  src/pages/paxDetail/addToWatchList/AddToWatchlist.js
  src/pages/paxDetail/changeHitStatus/ChangeHitStatus.js
  src/pages/paxDetail/createManualHit/CreateManualHit.js
  src/pages/paxDetail/downloadReports/DownloadReports.js
  src/pages/paxDetail/notification/Notification.js
  src/pages/paxDetail/summary/Summary.js
  src/pages/paxDetail/uploadAttachment/AttachmentModal.js
  src/pages/poe/POE.js
  src/pages/tools/queryrules/QRModal.js
  src/pages/tools/queryrules/Queries.js
  src/pages/tools/queryrules/Rules.js
  src/pages/tools/watchlist/WLModal.js
  src/pages/tools/watchlist/Watchlist.js
  src/pages/vetting/Vetting.css
  src/pages/vetting/Vetting.js
  src/utils/utils.js
  yarn.lock
Labels: yarn install
