Repository US-CBP/GTAS-UI, pull requests merged in 2020-10, with the labels that each got.

#302 Fix/257
  .idea/GTAS-UI_cloned_20200827_1.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/components/header/Header.js
  src/components/header/Header.scss
  src/components/inputs/text/Text.js
  src/images/WCO_GTAS_header_brand.png
  src/pages/vetting/Vetting.css
  src/pages/vetting/Vetting.js
Labels: enhancement

#310 Linkanalysis
  .idea/GTAS-UI_cloned_20200827_1.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/components/graph/Graph.js
  src/components/graph/structure.js
  src/components/paxInfo/PaxInfo.js
  src/pages/paxDetail/PaxDetail.js
  src/pages/paxDetail/linkAnalysis/LinkAnalysis.js
  src/services/serviceWrapper.js
Labels: backend

#340 loader statistics data clean up
  src/pages/admin/loaderStats/LoaderStats.js
  src/services/serviceWrapper.js
Labels: backend

#345 init
  src/components/stepper/Stepper.js
  src/components/stepper/Stepper.scss
  src/pages/paxDetail/PaxDetail.js
Labels: 2.0 Burndown
