Repository US-CBP/GTAS-UI, pull requests merged in 2021-03, with the labels that each got.

#669 disable sort on vetting col
  src/pages/vetting/Vetting.js
Labels: 3 - Review, bug 🐞

#676 Update/password constraints
  src/App.scss
  src/components/PasswordConstraints/PasswordConstraints.js
  src/components/PasswordConstraints/PasswordConstraints.scss
  src/components/errorText/ErrorText.scss
  src/pages/admin/manageUsers/changePassword/ChangePassword.js
  src/pages/admin/manageUsers/changePassword/ChangePassword.scss
  src/pages/login/ResetPassword.js
  src/utils/utils.js
Labels: enhancement

#679 Fix/translation fetch
  package-lock.json
  package.json
  src/components/header/Header.js
  src/components/header/Header.scss
  src/context/data/LookupContext.js
  src/context/translation/LiveEditContext.js
  src/fetch/index.d.ts
  src/fetch/index.js
  src/i18n.js
  src/pages/home/Home.js
  src/pages/login/Login.js
  src/services/baseService.js
  src/services/genericService.js
Labels: bug 🐞, yarn/npm install

#682 Fix/datepicker layout
  src/App.scss
  src/components/filterForm2/FilterForm.css
  src/pages/admin/auditLog/AuditLog.js
  src/pages/admin/errorLog/ErrorLog.js
  src/pages/vetting/Vetting.css
Labels: bug 🐞

#684 Inline input validation
  package-lock.json
  src/App.scss
  src/components/icons/InputValidationIcon.js
  src/components/inputs/text/Text.js
  src/components/labelledInput/LabelledInput.js
  src/components/overlay/Overlay.js
  src/components/overlay/Overlay.scss
  src/pages/admin/manageUsers/UserModal.js
  yarn.lock
Labels: 3 - Review, enhancement

#689 upgrade react bootstrap to 1.5.0 from rc
  package-lock.json
  package.json
  src/components/stepper/Stepper.js
Labels: 3 - Review, yarn/npm install

#680 CardWithTable - don't return overlays for fields without tooltips
  src/App.scss
  src/components/cardWithTable/CardWithTable.js
  src/components/overlay/Overlay.scss
  src/components/paxInfo/PaxInfo.js
  src/components/tooltipWrapper/TooltipWrapper.js
  src/pages/flightPax/FlightPax.js
  src/pages/flights/Flights.js
Labels: Housekeeping, enhancement, performance

#699 fix translation modal css
  src/components/inputs/label/Label.js
  src/components/labelledInput/LabelledInput.css
  src/components/labelledInput/LabelledInput.js
  src/pages/home/LangModal.js
Labels: bug 🐞

#705 fix dob filter, left-zero-pad dates
  src/pages/flightPax/FlightPax.js
  src/utils/constants.js
  src/utils/utils.js
Labels: bug 🐞

#707 remove filter
  src/pages/flightPax/FlightPax.js
Labels: bug 🐞

#708 sort by last name
  src/pages/vetting/Vetting.js
Labels: bug 🐞

#710 Feat/grid filters
  src/pages/admin/manageUsers/ManageUsers.js
  src/pages/tools/queryrules/Queries.js
  src/pages/tools/queryrules/QueryRules.css
  src/pages/tools/queryrules/Rules.js
  src/pages/tools/watchlist/Watchlist.js
Labels: enhancement

#700 Fix/seat chart translations
  src/components/seatChart/SeatChart.js
  src/components/seatChart/SeatChart.scss
  src/components/seatChart/legend/Legend.js
  src/components/seatChart/searchSeat/SearchSeat.js
  src/components/seatChart/seat/SeatInfoModal.js
  src/components/seatChart/seatChartCard/SeatChartCard.js
  src/components/seatChart/seatInfo/SeatInfo.js
  src/pages/admin/settings/Settings.js
Labels: bug 🐞
