Repository US-CBP/GTAS-UI, pull requests merged in 2021-04, with the labels that each got.

#714 Fix/download fix
  src/services/serviceWrapper.js
Labels: 4 - Done

#721 fix references to SharedArrayBuffer
  public/index.html
Labels: Housekeeping

#722 Fixed dob filter
  src/pages/tools/watchlist/Watchlist.js
Labels: bug 🐞

#718 Prevent page refreshing when pressing enter
  src/components/header/Header.js
Labels: bug 🐞

#713 Fix for multi-request vetting issue
  src/pages/vetting/Vetting.js
Labels: Housekeeping

#725 Fix/seat chart centered
  src/components/seatChart/SeatChart.js
  src/components/seatChart/SeatChart.scss
Labels: bug 🐞

#736 Fix/link analysis perf
  src/components/graph/Graph.css
  src/components/graph/Graph.js
  src/components/graph/structure.js
Labels: bug 🐞
