Repository US-CBP/GTAS-UI, pull requests merged in 2021-06, with the labels that each got.

#791 Misc Table layout issues
  src/App.scss
  src/components/countdownBadge/CountdownBadge.js
  src/components/flightBadge/FlightBadge.js
  src/pages/vetting/Vetting.js
  src/pages/vetting/biographicInfo/BiographicInfo.js
  src/pages/vetting/biographicInfo/BiographicInfo.scss
Labels: bug 🐞, enhancement

#798 promoted seatchart to page
  src/App.js
  src/components/paxInfo/PaxInfo.js
  src/pages/flightPax/FlightPax.js
  src/pages/seatChart/SeatChart.js
  src/pages/seatChart/SeatChart.scss
  src/pages/seatChart/flightInfo/FlighInfo.js
  src/pages/seatChart/legend/Legend.js
  src/pages/seatChart/legend/Legend.scss
  src/pages/seatChart/searchSeat/SearchSeat.js
  src/pages/seatChart/seat/Seat.js
  src/pages/seatChart/seat/Seat.scss
  src/pages/seatChart/seat/SeatInfoModal.js
  src/pages/seatChart/seatChartCard/SeatChartCard.js
  src/pages/seatChart/seatInfo/SeatInfo.js
  src/pages/seatsMap/SeatsMap.js
Labels: Housekeeping

#799 fix icon dimensions
  src/components/lazyImage/LazyImage.js
  src/components/lazyImage/LazyImage.scss
Labels: bug 🐞

#794 fix broken timer sort
  src/pages/vetting/Vetting.js
Labels: bug 🐞

#796 Fix/flight number cols
  src/pages/flights/Flights.js
  src/pages/paxDetail/flightHistory/FlightHistory.js
  src/pages/paxDetail/pnr/PNR.js
  src/pages/search/Search.js
  src/pages/seatChart/SeatChart.js
  src/pages/seatChart/seatChartCard/SeatChartCard.js
  src/pages/tools/queryrules/QRModal.js
  src/pages/vetting/Vetting.js
Labels: bug 🐞

#768 Fix/table no data rows
  src/components/table/Table.js
  src/components/table/table-utils.js
Labels: Housekeeping, bug 🐞

#805 Fix/icons in links
  src/App.scss
  src/components/flightBadge/FlightBadge.js
  src/components/flightBadge/FlightBadge.scss
  src/components/paxInfo/PaxInfo.js
  src/components/stepper/Stepper.js
  src/components/table/Table.js
  src/components/tooltipWrapper/TooltipWrapper.js
  src/pages/admin/lookoutLanes/LookoutModal.js
  src/pages/vetting/Vetting.js
  src/pages/vetting/biographicInfo/BiographicInfo.js
  src/utils/constants.js
Labels: bug 🐞

#810 Fix/edit user name validation
  src/pages/admin/manageUsers/UserModal.js
Labels: bug 🐞

#813 Fix/header alignment
  src/components/title/Title.css
  src/pages/admin/fileDownload/fileDownload.css
  src/pages/paxDetail/PaxDetail.scss
Labels: bug 🐞

#814 Add flightpax link and flight number to POE tile
  src/components/kanban/Kanban.js
Labels: 4 - Done, enhancement

#817 Fix/lookout promote pax name
  src/pages/vetting/Vetting.js
Labels: 3 - Review, bug 🐞

#818 minor - correct missing blur on paxdetail sidebar
  src/App.scss
  src/components/filterForm2/FilterForm.css
  src/components/sidenavContainer/SidenavContainer.scss
Labels: bug 🐞

#820 fix missing table filter cols
  src/components/table/Table.js
Labels: 3 - Review, bug 🐞

#823 Pos/Neg rule count added to table
  src/components/kanban/Kanban.js
  src/pages/tools/queryrules/Rules.js
Labels: backend, enhancement

#822 Fix/unauthed request security
  src/components/header/Header.js
  src/components/xl8/Xl8.js
  src/context/user/UserContext.js
  src/i18n.js
  src/pages/login/ForgotPassword.js
  src/pages/login/Login.js
  src/services/genericService.js
  src/services/serviceWrapper.js
Labels: 3 - Review, backend, bug 🐞

#825 hide action column when filter by approved/rejected status
  src/components/table/Table.js
  src/pages/admin/signUpRequests/SignUpRequests.js
  src/utils/constants.js
Labels: 4 - Done, bug 🐞

#781 Feat/translation default text
  src/pages/home/LangModal.js
  src/pages/lang/LanguageEditor.js
Labels: backend, enhancement

#827 rem erroneous space in translation return
  src/components/countdownBadge/CountdownBadge.js
  src/components/xl8/Xl8.js
Labels: 3 - Review, bug 🐞

#829 Poe horizontal scroll shift
  src/components/kanban/Kanban.css
  src/components/kanban/Kanban.js
Labels: enhancement

#834 Fix/login input width
  src/pages/login/Login.js
  src/pages/login/Login.scss
Labels: bug 🐞
