Repository US-CBP/GTAS-UI, pull requests merged in 2021-02, with the labels that each got.

#636 Adds missing header to attachments
  src/services/baseService.js
  src/services/serviceWrapper.js
Labels: 4 - Done

#638 reformatted the dob
  src/pages/tools/watchlist/WLModal.js
Labels: bug

#641 Fixed middle name display issue
  src/components/seatChart/SeatChart.js
  src/components/seatChart/searchSeat/SearchSeat.js
  src/components/seatChart/seatInfo/SeatInfo.js
Labels: backend

#653 Fix for download attachment bug
  src/pages/admin/fileDownload/FileDownload.js
  src/pages/paxDetail/uploadAttachment/UploadAttachment.js
  src/services/genericService.js
  src/services/serviceWrapper.js
Labels: 4 - Done, bug

#659 fix license location
  license.txt
Labels: Housekeeping

#661 null check on search comparison
  src/components/seatChart/searchSeat/SearchSeat.js
Labels: 3 - Review, bug 🐞

#662 set the initial state for the signup request filterform
  src/pages/admin/signUpRequests/SignUpRequests.js
Labels: 3 - Review, bug 🐞

#663 remove extra space after minus sign
  src/components/countdownBadge/CountdownBadge.js
Labels: 3 - Review, bug 🐞

#648 Add UTC offset. This allows the backend to use DOB instead of AGE on queries
  src/pages/tools/queryrules/QRModal.js
Labels: 3 - Review

#665 fix start date bug, fix date calc, fix toggle ref
  src/pages/vetting/Vetting.js
Labels: 3 - Review, bug 🐞

#660 reset dp layout, fix background scroll behavior
  src/App.scss
  src/components/filterForm2/FilterForm.css
Labels: 3 - Review, bug 🐞

#640 correct handling for bad paths
  src/App.js
  src/components/cardWithTable/CardWithTable.js
  src/components/flightBadge/FlightBadge.js
  src/components/paxInfo/PaxInfo.js
  src/components/stepper/Stepper.js
  src/components/tooltipWrapper/TooltipWrapper.js
  src/pages/admin/Admin.js
  src/pages/flightPax/FlightPax.js
  src/pages/flights/Flights.js
  src/utils/utils.js
Labels: 3 - Review, Housekeeping
