Repository US-CBP/GTAS-UI, pull requests merged in 2021-05, with the labels that each got.

#756 header vertical alignment
  src/components/header/Header.js
  src/components/header/Header.scss
Labels: enhancement

#755 Reorder flight table column
  src/pages/flights/Flights.js
Labels: enhancement

#740 Fix/multiple seats per pax
  src/components/paxInfo/PaxInfo.js
  src/components/seatChart/SeatChart.js
  src/pages/paxDetail/PaxDetail.js
Labels: bug 🐞, enhancement

#758 merge master
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code-quality.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: DOCS

#766 add 3 missing flags
  public/flags/country/BES.svg
  public/flags/country/CUW.svg
  public/flags/country/SXM.svg
Labels: bug 🐞

#769 carrier name from lookup in flightpax sidebar
  src/pages/flightPax/FlightPax.css
  src/pages/flightPax/FlightPax.js
Labels: enhancement

#773 Fix/login background
  src/components/filterForm2/FilterForm.css
  src/components/hitsBadge/HitsBadge.css
  src/components/sidenavContainer/SidenavContainer.scss
  src/pages/login/Login.js
  src/pages/login/Login.scss
Labels: enhancement

#777 hide the datetime picker's calendar popover
  src/components/filterForm2/FilterForm.css
Labels: bug 🐞

#770 add link to seat chart on flightpax
  src/components/seatChart/SeatChart.js
  src/pages/flightPax/FlightPax.css
  src/pages/flightPax/FlightPax.js
  src/pages/flights/Flights.js
  src/utils/constants.js
Labels: enhancement

#761 Fixes for hit category default sort and date range values not passed
  src/components/filterForm2/FilterForm.js
  src/pages/vetting/Vetting.js
  src/utils/utils.js
Labels: bug 🐞

#785 Login - update the layout text, remove unused images
  src/images/WCO_GTAS_header_brand.svg
  src/images/WCO_flag.svg
  src/pages/login/Login.js
  src/pages/login/Login.scss
Labels: enhancement

#788 QBRB - bypass favorites filter for query builder calls
  src/context/data/LookupContext.js
  src/pages/tools/queryrules/QRModal.js
Labels: bug 🐞

#784 Vetting - Hits col data truncated
  src/pages/vetting/Vetting.css
  src/pages/vetting/Vetting.js
Labels: backend, enhancement

#776 remove lane name xl8 tags
  src/components/kanban/Kanban.js
Labels: bug 🐞
